/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SeedImport } from './routes/seed'
import { Route as AppImport } from './routes/app'
import { Route as IndexImport } from './routes/index'
import { Route as AppHomeImport } from './routes/app.home'
import { Route as AppCreateImport } from './routes/app.create'

// Create/Update Routes

const SeedRoute = SeedImport.update({
  path: '/seed',
  getParentRoute: () => rootRoute,
} as any)

const AppRoute = AppImport.update({
  path: '/app',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AppHomeRoute = AppHomeImport.update({
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)

const AppCreateRoute = AppCreateImport.update({
  path: '/create',
  getParentRoute: () => AppRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/app': {
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/seed': {
      preLoaderRoute: typeof SeedImport
      parentRoute: typeof rootRoute
    }
    '/app/create': {
      preLoaderRoute: typeof AppCreateImport
      parentRoute: typeof AppImport
    }
    '/app/home': {
      preLoaderRoute: typeof AppHomeImport
      parentRoute: typeof AppImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AppRoute.addChildren([AppCreateRoute, AppHomeRoute]),
  SeedRoute,
])

/* prettier-ignore-end */
